name: main
on: push
env:
  PYTHON_VERSION: "3.13"

jobs:
  test-infra:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      
      - name: Install dependencies (get)
        run: | 
          pip install -r compilethis-site/get-function/requirements.txt
          pip install pytest


      - name: Test get-function
        run: |
          cd compilethis-site/get-function
          pytest || true

      - name: Install dependencies (put)
        run: | 
          pip install -r compilethis-site/put-function/requirements.txt
          pip install pytest


      - name: Test put-function
        run: |
          cd compilethis-site/put-function
          pytest || true

  build-and-deploy-infra:
    needs: test-infra
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: sam build
        working-directory: compilethis-site
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
        working-directory: compilethis-site

  build-and-deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ctwebsite11002
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: site-code